
MD5_Baseline : MD5_baseline.o
		g++ -g -std=c++11 -Wall -Wextra -Werror -o MD5_Baseline MD5_baseline.o -I.

MD5_baseline.o : MD5_baseline.cpp
		g++ -g -c -std=c++11 -Wall -Wextra -Werror MD5_baseline.cpp -I.

zap :
		rm MD5_Baseline
		rm MD5_Baseline.o
